#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     touch,          sensorEV3_Touch, modeEV3Bump)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          motorL,        tmotorEV3_Large, openLoop, driveRight, encoder)
#pragma config(Motor,  motorC,          motorR,        tmotorEV3_Large, openLoop, driveLeft, encoder)
#pragma config(Motor,  motorD,          motorG,        tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void printDis() {

  displayBigTextLine(1, "Current %f", getBatteryCurrent());
  displayBigTextLine(3, "Voltage: %f", getBatteryVoltage() );




}


task main() {

setMotorSpeed(motorL, 100);
setMotorSpeed(motorR, 100);



  while (getBatteryVoltage() > 7.8) {
		printDis();
  }
setMotorSpeed(motorL, 0);
setMotorSpeed(motorR, 0);
playImmediateTone(400, 20);



}
